# Generated by Django 5.2 on 2025-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='stores',
            field=models.ManyToManyField(related_name='books', to='books.store'),
        ),
    ]
